[workspace]
resolver = "2"

members = ["crates/*"]

[workspace.package]
edition = "2021"
authors = ["Cardinal"]
homepage = "https://alephzero.org"
license = "Apache-2.0"
categories = ["cryptography"]
repository = "https://github.com/Cardinal-Cryptography/zkOS"

[workspace.dependencies]
console_error_panic_hook = { version = "0.1.7" }
criterion = { version = "0.5.1" }
getrandom = { version = "0.2" }
halo2_poseidon = { git = "ssh://git@github.com/Cardinal-Cryptography/poseidon-gadget", branch = "poseidon2-pow7" }
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0", default-features = false }
human_bytes = { version = "0.4.3", default-features = false }
itertools = { version = "0.13.0" }
once_cell = { version = "1.20.2" }
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3.1" }
rand_core = { version = "0.6.4" }
rayon = { version = "1.8" }
ruint = { version = "1" }
sha2 = { version = "0.10.8" }
sha3 = { version = "0.10" }
static_assertions = { version = "1.1.0" }
strum = { version = "0.26.3" }
strum_macros = { version = "0.26.3" }
thiserror = { version = "1.0.61" }

# Local dependencies
shielder-circuits = { path = "crates/shielder-circuits" }
transcript = { path = "crates/transcript" }
