---
#  This workflow checks if vars and secrets are present and fails if one is empty.
#  It should be included as a first step in all the workflows.
name: Check vars and secrets
on:
  workflow_call:

jobs:
  main:
    name: Check available vars and secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Check secrets
        run: |
          if [[ \
            -z '${{ secrets.SSH_KEY }}' || \
            -z '${{ secrets.SLACK_WEBHOOK_ZKOS }}'
          ]]; then
            echo '!!! Some repository secrets are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi
