---
name: Run linter and tests for all Rust crates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # Run formatter and linter for all crates, and unit tests for all simple crates, that,
  # in particular, do not require anvil node to be running.
  # For shielder-circuit crate, we run tests and build the binary for measuring circuits.
  rust-checks-and-unit-tests:
    name: Run lints and tests
    # runs-on: [self-hosted, Linux, X64, large]
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    env:
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run linter and formatter
        run: |
          make lint

      # Shielder-circuits part
      - name: Build shielder-circuits package
        run: make build && make test

      - name: Upload circuit measurements binary
        uses: actions/upload-artifact@v4
        with:
          path: target/release/measure-circuits
          name: measure-circuits
          retention-days: 1
