---
name: Run linter and tests for all Rust crates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  main:
    name: Run lints and tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      RUSTC_WRAPPER: sccache

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          ssh-private-key: ${{ secrets.ZKOS_GH_TOKEN }}

      - name: Ensure formatting is correct
        run: cargo +nightly fmt --all --check

      - name: Run linter
        run: make lint

      - name: Build shielder-circuits package
        run: make build && make test

      - name: Upload circuit measurements binary
        uses: actions/upload-artifact@v4
        with:
          path: target/release/measure-circuits
          name: measure-circuits
          retention-days: 1
