---
name: Nightly E2E tests run on testnet

on:
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  circuits-benches:
    name: Run benches for shielder-circuits crate
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    env:
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Run benches for shielder-circuits
        run: make bench

  slack-notification:
    name: Slack notification
    runs-on: ubuntu-22.04
    needs: [circuits-benches]
    if: >
      !cancelled() &&
      github.event_name != 'workflow_dispatch'
    steps:
      - name: Send Slack message
        uses: Cardinal-Cryptography/github-actions/slack-notification@v7
        with:
          notify-on: "failure"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_ZKOS }}
